feat: add ai-assistant link
opensource-f2f/website pull request #68
Opened 2024-03-05 06:30 UTC by xiaowangxiaowang256256

#62 add ai-assistant link

2024-03-05 09:50 UTC, sxzz requested changes
为本功能引入 element-plus 似乎有些没必要，考虑到它会增加 bundle size
因为我们有了 unpluin-icons，所以没有必要使用 @element-plus/icons-vue 
我们可以考虑把版权声明页面底部

2024-03-06 02:43 UTC, LinuxSuRen approved these changes
LGTM from a user perspective.

2024-03-06 07:46 UTC, LinuxSuRen commented on src/components/app-header.vue
> +                alt="NetEase Music"
这里的文案和图片不一致

2024-03-06 07:54 UTC, xiaowangxiaowang256256 commented on src/components/app-header.vue
> +                alt="NetEase Music"
> 这里的文案和图片不一致

该问题已修复

2024-03-06 09:17 UTC, sxzz approved these changes
Tweaked some design details of AI assistant

- Moved to the right-bottom corner.
- Memorize the state of if show AI assistant

2024-03-06 09:19 UTC, merged